name: Build, Check And Deploy to Prod

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: npm install, and build
      run: |
        npm install
        npm run build

    - name: Deploy to Prod s3
      run: |
        aws s3 sync dist s3://$AWS_S3_BUCKET --region us-east-1 --delete
      env:
        AWS_DEFAULT_REGION: 'us-east-1'
        AWS_S3_BUCKET: appeals-app-all
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}